// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	book "github.com/pranavkonde/LMS-Go/book"

	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, req
func (_m *Service) Create(ctx context.Context, req book.CreateRequest) error {
	ret := _m.Called(ctx, req)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, book.CreateRequest) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteByID provides a mock function with given fields: ctx, id
func (_m *Service) DeleteByID(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *Service) FindByID(ctx context.Context, id string) (book.FindByIDResponse, error) {
	ret := _m.Called(ctx, id)

	var r0 book.FindByIDResponse
	if rf, ok := ret.Get(0).(func(context.Context, string) book.FindByIDResponse); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(book.FindByIDResponse)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx
func (_m *Service) List(ctx context.Context) (book.ListResponse, error) {
	ret := _m.Called(ctx)

	var r0 book.ListResponse
	if rf, ok := ret.Get(0).(func(context.Context) book.ListResponse); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(book.ListResponse)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, req
func (_m *Service) Update(ctx context.Context, req book.UpdateRequest) error {
	ret := _m.Called(ctx, req)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, book.UpdateRequest) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewService interface {
	mock.TestingT
	Cleanup(func())
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewService(t mockConstructorTestingTNewService) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
